Update Dockerfile-new

diff --git a/backend-app/Dockerfile-new b/backend-app/Dockerfile-new
--- a/backend-app/Dockerfile-new
+++ b/backend-app/Dockerfile-new
@@ -1,4 +1,4 @@
 FROM alpine:3.20
 RUN echo "test run 5"
 RUN echo "===== TCP" && (nc -zv -w 5 192.168.10.141 8081 || echo "TCP FAILED")
-RUN echo "===== DOWNLOAD" && (wget -qO- -T 10 http://dev.bp:8081/repository/test/hello.txt || echo "DOWNLOAD FAILED")
+RUN echo "===== DOWNLOAD" && (wget -qO- -T 10 http://dev.bp:8081/repository/test/hello.txt || echo "DOWNLOAD FAILED" && exit 1)
